import type { QAContext, QAExtractedFile } from "../types";

const GENERATED_CODE_MARKER =
  "The following code files were generated by previous agents.";

export class QAContextService {
  extractContext = ({ userMessage }: { userMessage: string }): QAContext => {
    const extractedFiles = this.extractGeneratedFiles({ userMessage });
    const requestSummary = this.extractRequestSummary({ userMessage });

    return {
      requestSummary,
      extractedFiles,
    };
  };

  private extractRequestSummary = ({
    userMessage,
  }: {
    userMessage: string;
  }): string => {
    const markerIndex = userMessage.indexOf(GENERATED_CODE_MARKER);
    if (markerIndex === -1) {
      return userMessage.trim();
    }

    return userMessage.slice(0, markerIndex).trim();
  };

  private extractGeneratedFiles = ({
    userMessage,
  }: {
    userMessage: string;
  }): QAExtractedFile[] => {
    const files: QAExtractedFile[] = [];

    const fileBlockRegex =
      /- ([^\n]+?) \(([^)]+)\): ([^\n]*)\n```([^\n]*)\n([\s\S]*?)```/g;

    let match: RegExpExecArray | null = fileBlockRegex.exec(userMessage);
    while (match) {
      const filePath = match[1]?.trim();
      const language = (match[4] || match[2] || "text").trim();
      const description = (match[3] || "").trim();
      const code = (match[5] || "").trim();

      if (filePath && code) {
        files.push({
          filePath,
          language,
          description,
          code,
        });
      }

      match = fileBlockRegex.exec(userMessage);
    }

    return files;
  };
}
